export type Country = { name: string; fijo: boolean; movil: boolean };

export const COUNTRIES: Country[] = [
  { name: "Alemania", fijo: true, movil: true },
  { name: "Andorra", fijo: true, movil: true },
  { name: "Argentina", fijo: true, movil: true },
  { name: "Austria", fijo: true, movil: true },
  { name: "Bélgica", fijo: true, movil: true },
  { name: "Brasil", fijo: true, movil: true },
  { name: "Bulgaria", fijo: true, movil: true },
  { name: "Canadá", fijo: true, movil: true },
  { name: "China", fijo: true, movil: true },
  { name: "Chipre", fijo: true, movil: true },
  { name: "Colombia", fijo: true, movil: true },
  { name: "Corea del Sur", fijo: true, movil: true },
  { name: "Costa Rica", fijo: true, movil: true },
  { name: "Croacia", fijo: true, movil: true },
  { name: "Dinamarca", fijo: true, movil: true },
  { name: "Eslovaquia", fijo: true, movil: true },
  { name: "Eslovenia", fijo: true, movil: true },
  { name: "Estados Unidos", fijo: true, movil: true },
  { name: "Estonia", fijo: true, movil: true },
  { name: "Finlandia", fijo: true, movil: true },
  { name: "Francia", fijo: true, movil: true },
  { name: "Gran Bretaña", fijo: true, movil: true },
  { name: "Grecia", fijo: true, movil: true },
  { name: "Hong Kong", fijo: true, movil: true },
  { name: "Hungría", fijo: true, movil: true },
  { name: "India", fijo: true, movil: true },
  { name: "Irlanda", fijo: true, movil: true },
  { name: "Islandia", fijo: true, movil: true },
  { name: "Israel", fijo: true, movil: true },
  { name: "Italia", fijo: true, movil: true },
  { name: "Japón", fijo: true, movil: true },
  { name: "Kazajistán", fijo: true, movil: true },
  { name: "Liechtenstein", fijo: true, movil: true },
  { name: "Lituania", fijo: true, movil: true },
  { name: "Luxemburgo", fijo: true, movil: true },
  { name: "Marruecos", fijo: true, movil: false },
  { name: "México", fijo: true, movil: true },
  { name: "Noruega", fijo: true, movil: true },
  { name: "Nueva Zelanda", fijo: true, movil: true },
  { name: "Países Bajos", fijo: true, movil: true },
  { name: "Panamá", fijo: true, movil: true },
  { name: "Paraguay", fijo: true, movil: true },
  { name: "Perú", fijo: true, movil: true },
  { name: "Polonia", fijo: true, movil: true },
  { name: "Portugal", fijo: true, movil: true },
  { name: "República Checa", fijo: true, movil: true },
  { name: "República Dominicana", fijo: true, movil: true },
  { name: "Rumanía", fijo: true, movil: true },
  { name: "Rusia", fijo: true, movil: true },
  { name: "Singapur", fijo: true, movil: true },
  { name: "Suecia", fijo: true, movil: true },
  { name: "Suiza", fijo: true, movil: true },
  { name: "Tailandia", fijo: true, movil: true },
  { name: "Taiwán", fijo: true, movil: true },
  { name: "Uruguay", fijo: true, movil: true },
  { name: "Venezuela", fijo: true, movil: true },
];
