/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificacionRouteImport } from './routes/verificacion'
import { Route as PagoOkRouteImport } from './routes/pago-ok'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalPrivacidadRouteImport } from './routes/legal/privacidad'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalAvisoLegalRouteImport } from './routes/legal/aviso-legal'

const VerificacionRoute = VerificacionRouteImport.update({
  id: '/verificacion',
  path: '/verificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoOkRoute = PagoOkRouteImport.update({
  id: '/pago-ok',
  path: '/pago-ok',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/legal/privacidad',
  path: '/legal/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAvisoLegalRoute = LegalAvisoLegalRouteImport.update({
  id: '/legal/aviso-legal',
  path: '/legal/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pago-ok': typeof PagoOkRoute
  '/verificacion': typeof VerificacionRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pago-ok': typeof PagoOkRoute
  '/verificacion': typeof VerificacionRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pago-ok': typeof PagoOkRoute
  '/verificacion': typeof VerificacionRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pago-ok'
    | '/verificacion'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/privacidad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pago-ok'
    | '/verificacion'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/privacidad'
  id:
    | '__root__'
    | '/'
    | '/pago-ok'
    | '/verificacion'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/privacidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagoOkRoute: typeof PagoOkRoute
  VerificacionRoute: typeof VerificacionRoute
  LegalAvisoLegalRoute: typeof LegalAvisoLegalRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificacion': {
      id: '/verificacion'
      path: '/verificacion'
      fullPath: '/verificacion'
      preLoaderRoute: typeof VerificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago-ok': {
      id: '/pago-ok'
      path: '/pago-ok'
      fullPath: '/pago-ok'
      preLoaderRoute: typeof PagoOkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/legal/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aviso-legal': {
      id: '/legal/aviso-legal'
      path: '/legal/aviso-legal'
      fullPath: '/legal/aviso-legal'
      preLoaderRoute: typeof LegalAvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagoOkRoute: PagoOkRoute,
  VerificacionRoute: VerificacionRoute,
  LegalAvisoLegalRoute: LegalAvisoLegalRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
